name: MatchMakerTest

on: # 아래의 상황에서 action을 시작한다.
  push:
    branches:
      - test1
      - 'feature/**'
      - abcd
    paths-ignore:
      - 'workflows/**'      
  pull_request:
    branches:
      - test1
      - test2
    paths-ignore:
      - 'workflows/**'
  workflow_dispatch:

jobs: # actoion이 시작될 경우 진행될 과정
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
#          pip install -r requirements.txt
          pip install git+https://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@github.com/kc-softmax/mas-game-helper.git@main
      - name: Run tests with pytest
        run: pytest


$ git config --global user.name "youn7054a"
$ git config --global user.email "youn7054@gmail.com"