name: MatchMakerTest

on: # 아래의 상황에서 action을 시작한다.
  push:
    branches:
      - test1
      - 'feature/**'
      - abcd
    paths-ignore:
      - 'workflows/**'      
  pull_request:
    branches:
      - test1
      - test2
    paths-ignore:
      - 'workflows/**'
  workflow_dispatch:

jobs: # actoion이 시작될 경우 진행될 과정
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
